version: "3.9"
services:
  hockey-bot:
    build: .
    ports:
      - "443:443"
    env_file:
      - bot-vars.env
    command: ['npm', 'start']
  hockey-pg:
    image: postgres
    container_name: hockey-db-pg
    ports:
    - "5432:5432"
    env_file:
      - bot-vars.env
    volumes:
      - .env:/docker-entrypoint-initdb.d/.env
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  db_vol:
