version: "3.9"
services:
  hockey-bot:
    image: saf6260/hockey-js
    ports:
      - "443:443"
    volumes:
      - db_vol:/usr/app/datastore/
    env_file:
      - bot-vars.env
    command: ['npm', 'start']
volumes:
  db_vol:
