name: Digital Ocean Image Push On Master Merge

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout master
      uses: actions/checkout@master
        
    - name: Build container image
      run: docker build -t registry.digitalocean.com/scottalexfr/hockeyjs:$(echo $GITHUB_SHA | head -c7) .
      
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Log in to DigitalOcean Container Registry with short-lived credentials\
      shell: bash
      env: 
        ACCESS_TOKEN: ${{ secrets.DIGITALOCEN_ACCESS_TOKEN }}
      run: doctl registry login --expiry-seconds 600 -t "$ACCESS_TOKEN"
    
    - name: Debug display creds
      run: doctl registry repository list
      
    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/scottalexfr/hockeyjs
